# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 157805964+Normie69K@users.noreply.github.com
author_name: Normie69K
contract_name: carbonmarketplace
deployment_language: python
preset_name: starter
project_name: carbon-marketplace

